In [1]:
import numpy as np

<a href='https://stepik.org/lesson/24613/step/2'>Задание #1</a>

In [2]:
a = np.array([[1,0,0,0],
            [0,1,0,0],
            [0,0,1,0],
            [0,0,0,1]])
b = np.array([[1,2,3],
            [5,6,7],
            [9,10,11],
            [4,8,12]])
c = np.array([[3,0,0],
            [0,3,0],
            [0,0,3]])
matrix = ((2*a).dot(b)).dot(c)
matrix

array([[ 6, 12, 18],
       [30, 36, 42],
       [54, 60, 66],
       [24, 48, 72]])

<a href='https://stepik.org/lesson/24613/step/3'>Задание #2</a>

In [3]:
# ассоциативность
a = np.array([[1,2,3],[5,6,7],[9,10,11],[4,8,12]])
b = np.array([[1],[5],[9]])
c = np.array([[1,2,3,4,5,6]])

ab_c = (a.dot(b)).dot(c)
a_bc = a.dot(b.dot(c))

if ab_c.all() == a_bc.all():
    print('(A×B)×C=A×(B×C)')
else:
    print('(A×B)×C≠A×(B×C)')

(A×B)×C=A×(B×C)


<a href='https://stepik.org/lesson/24613/step/4'>Задание #3</a>

In [4]:
# дистрибутивность
a = np.array([[1,2,3],[5,6,7],[9,10,11],[4,8,12]])
b = np.array([[1],[5],[9]])
d = np.array([[3],[4],[1]])

e1 = a.dot(b+d)
e2 = a.dot(b) + a.dot(d)

if e1.all() == e2.all():
    print('Каждый элемент E1 равен элементу E2, стоящему на таком же месте')
elif e1.all() <= e2.all():
    print('Каждый элемент E1 меньше элемента E2, стоящего на таком же месте')
elif e1.all() >= e2.all():
    print('Каждый элемент E1 больше элемента E2, стоящего на таком же месте')

Каждый элемент E1 равен элементу E2, стоящему на таком же месте


<a href='https://stepik.org/lesson/24613/step/5'>Задание #4</a>

In [5]:
f1 = np.array([[-6, 2, 5], [-4, 1, -5], [-3, -2, 8]])
f2 = np.array([[5, 2, -5], [-8, -10, 4], [9, 7, 1]])

f1_f2 = f1.dot(f2)
f2_f1 = f2.dot(f1)

print(f1_f2)

print(f2_f1)

[[ -1   3  43]
 [-73 -53  19]
 [ 73  70  15]]
[[-23  22 -25]
 [ 76 -34  42]
 [-85  23  18]]


### Как создать массив:

```
- array(object) — n-мерный массив из любой (возможно, вложенной) последовательности
- eye(N, M=N, k=0) -- двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях. Число столбцов M по умолчанию
равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа для верхних диагоналей и отрицательные для нижних)
- zeros(shape) -- новый массив указанной формы, заполненный нулями,
- ones(shape) -- новый массив указанной формы, заполненный единицами,
full(shape, fill_value) -- новый массив указанной формы, заполненный fill_value.
```

<a href='https://stepik.org/lesson/16462/step/5'>Задание #1</a>

In [6]:
a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
a = a * 2
a = a + b
a

array([[2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])