In [103]:
import numpy as np
from urllib.request import urlopen
import pandas as pd

<a href='https://stepik.org/lesson/24613/step/2'>Задание #1</a>

In [2]:
a = np.array([[1,0,0,0],
            [0,1,0,0],
            [0,0,1,0],
            [0,0,0,1]])
b = np.array([[1,2,3],
            [5,6,7],
            [9,10,11],
            [4,8,12]])
c = np.array([[3,0,0],
            [0,3,0],
            [0,0,3]])
matrix = ((2*a).dot(b)).dot(c)
matrix

array([[ 6, 12, 18],
       [30, 36, 42],
       [54, 60, 66],
       [24, 48, 72]])

<a href='https://stepik.org/lesson/24613/step/3'>Задание #2</a>

In [3]:
# ассоциативность
a = np.array([[1,2,3],[5,6,7],[9,10,11],[4,8,12]])
b = np.array([[1],[5],[9]])
c = np.array([[1,2,3,4,5,6]])

ab_c = (a.dot(b)).dot(c)
a_bc = a.dot(b.dot(c))

if ab_c.all() == a_bc.all():
    print('(A×B)×C=A×(B×C)')
else:
    print('(A×B)×C≠A×(B×C)')

(A×B)×C=A×(B×C)


<a href='https://stepik.org/lesson/24613/step/4'>Задание #3</a>

In [4]:
# дистрибутивность
a = np.array([[1,2,3],[5,6,7],[9,10,11],[4,8,12]])
b = np.array([[1],[5],[9]])
d = np.array([[3],[4],[1]])

e1 = a.dot(b+d)
e2 = a.dot(b) + a.dot(d)

if e1.all() == e2.all():
    print('Каждый элемент E1 равен элементу E2, стоящему на таком же месте')
elif e1.all() <= e2.all():
    print('Каждый элемент E1 меньше элемента E2, стоящего на таком же месте')
elif e1.all() >= e2.all():
    print('Каждый элемент E1 больше элемента E2, стоящего на таком же месте')

Каждый элемент E1 равен элементу E2, стоящему на таком же месте


<a href='https://stepik.org/lesson/24613/step/5'>Задание #4</a>

In [5]:
f1 = np.array([[-6, 2, 5], [-4, 1, -5], [-3, -2, 8]])
f2 = np.array([[5, 2, -5], [-8, -10, 4], [9, 7, 1]])

f1_f2 = f1.dot(f2)
f2_f1 = f2.dot(f1)

print(f1_f2)

print(f2_f1)

[[ -1   3  43]
 [-73 -53  19]
 [ 73  70  15]]
[[-23  22 -25]
 [ 76 -34  42]
 [-85  23  18]]


### Как создать массив:

In [11]:
# - array(object) — n-мерный массив из любой (возможно, вложенной) последовательности
# - eye(N, M=N, k=0) — двумерный массив с N строками с единицами на диагонали и нулями во всех остальных позициях.
# Число столбцов M по умолчанию равно N, k — сдвиг диагонали (0 для основной диагонали, положительные числа
# для верхних диагоналей и отрицательные для нижних)
# - zeros(shape) — новый массив указанной формы, заполненный нулями,
# - ones(shape) — новый массив указанной формы, заполненный единицами,
# - full(shape, fill_value) — новый массив указанной формы, заполненный fill_value.

<a href='https://stepik.org/lesson/16462/step/5'>Задание #1</a>

In [13]:
a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
a = a * 2
a = a + b
a

array([[2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])

### Формы массива:

In [14]:
# a.flatten() — превращает массив в одномерный.
# a.T или a.transpose(*axes) — транспонирование (или смена порядка осей в случае, когда размерность массива больше двух).
# a.reshape(shape) — смена формы массива. Массив "распрямляется" и построчно заполняется в новую форму.

In [20]:
import random
w = np.array(random.sample(range(1000), 12)) # одномерный массив из 12 случайных чисел от 1 до 1000
print('===1===')
print(w)
# reshape((2,2,3)) количество матриц, количество строк в каждой матрице, количество столбцов в каждой матрице
w = w.reshape((2,2,3))
print('===2===')
print(w)
print('===3===')
print(w.transpose(0,2,1))

===1===
[712 360 329 641 728 548 246 437 982 107 528 194]
===2===
[[[712 360 329]
  [641 728 548]]

 [[246 437 982]
  [107 528 194]]]
===3===
[[[712 641]
  [360 728]
  [329 548]]

 [[246 107]
  [437 528]
  [982 194]]]


<a href='https://stepik.org/lesson/16462/step/7'>Задание #2</a>

In [62]:
a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
a = a * 2
mat = a + b
mat = np.reshape(mat, (12, 1))
print(mat)

[[2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [68]:
a = np.eye(3, 4, k=0)
b = np.eye(3, 4, k=1)
a = a * 2
mat = a + b

In [ ]:
print(mat.reshape(-1,1))

In [ ]:
print(mat.reshape(12,1))

In [ ]:
print(mat.reshape(mat.size,1))

### Основные методы ndarray

**Базовые статистики**

a.min(axis=None), a.max(axis=None), a.mean(axis=None), a.std(axis=None) — минимум, максимум, среднее арифметическое
и стандартное отклонение вдоль указанной оси. По умолчанию ось не указана и статистика считается по всему массиву.
a.argmin(axis=None), a.argmax(axis=None) — индексы минимального и максимального элемента.

a.sum(axis=None), a.prod(axis=None) — сумма и произведение всех элементов вдоль указанной оси. a.cumsum(axis=None),
a.cumprod(axis=None) — частичные суммы и произведения

**Линейная алгебра**
Пакет numpy.linalg содержит большую часть стандартных операций и разложений матриц.
Некоторые самые популярные функции вынесены в корень пакета NumPy.

- a.dot(b) — матричное произведение двух массивов (размерности должны быть согласованы)
- linalg.matrix_power(M, n) — возведение матрицы M в степень n
- a.T — транспонирование
- linalg.norm(a, ord=None) — норма матрицы a, по умолчанию норма Фробениуса для матриц и L2-норма для векторов
- linalg.inv(a) — матрица, обратная к a (если a необратима, выбрасывается LinAlgError; псевдообратная считается через linalg.pinv(a))

<a href='https://stepik.org/lesson/16462/step/9'>Задание #3</a>

In [94]:
X = np.array([[8,  7,  7], [14,  4,  6]])
Y = np.array([[5, 5, 1], [5, 2, 6], [3, 3, 9], [1, 4, 6]])

In [95]:
if X.shape[1] == Y.shape[1]:
    print(X.dot(Y.transpose()))
else:
    print('matrix shapes do not match')

[[ 82  96 108  78]
 [ 96 114 108  66]]


In [96]:
try:
    print(X.dot(Y.T))
except ValueError:
    print("matrix shapes do not match")

[[ 82  96 108  78]
 [ 96 114 108  66]]


In [97]:
print(X.dot(Y.T) if X.shape[1]==Y.shape[1] else "matrix shapes do not match")

[[ 82  96 108  78]
 [ 96 114 108  66]]


### Как считать данные из файла:

In [ ]:
# "sbux.csv" — имя файла (или сюда же можно передать объект файла), из которого считываются данные.
# usecols — список колонок, которые нужно использовать. Если параметр не указан, считываются все колонки.
# skiprows — количество рядов в начале файла, которые нужно пропустить. В нашем случае пропущен ряд заголовков.
# По умолчанию (если значение параметра не указано явно) skiprows = 0.
# delimiter — разделитель столбцов в одной строке, в csv-файлах это запятая, по умолчанию разделителем
# является любой пробел (в том числе — знак табуляции).
# dtype — словарь из названий колонок (переменных) и типов хранящихся в них значений.
# NumPy использует свою собственную систему типов, и названия именно этих типов нужно указать. По умолчанию функция попытается самостоятельно
# угадать, какому типу принадлежат подаваемые на вход значения.

sbux = np.loadtxt("sbux.csv", usecols=(0,1,4), skiprows=1, delimiter=",", dtype={'names': ('date', 'open', 'close'), 'formats': ('datetime64[D]', 'f4', 'f4')})

<a href='https://stepik.org/lesson/16462/step/11'>Задание #4</a>

In [113]:
f = urlopen('https://stepic.org/media/attachments/lesson/16462/boston_houses.csv')
df = np.loadtxt(f, delimiter=',', skiprows=1)
print(df.mean(axis=0))

[22.53280632  3.61352356 11.36363636  0.06916996  0.55469506  6.28463439
  3.79504269]


In [114]:
y = [0.5, 1, -0.5, -1.5, -1.5, -1]
s = 0
for i in y:
    s += i ** 2
print(s)

7.0


In [115]:
y = [0.5, 1, -0.5, -1.5, -1.5, -1]
s = 0
for i in y:
    s += abs(i)
print(s)

6.0
